server.port=${PORT:8080}
spring.datasource.url=jdbc:postgresql://ep-shy-snow-a1fzpmny.ap-southeast-1.aws.neon.tech/nestfinder_db?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Cdasqfi81vrc
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=5
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
jwt.secret=NestFinderSuperSecretKey2025NSECProjectMustBe256BitsLong!
jwt.expiration=86400000
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
spring.application.name=nestfinder-backend
